all : P2

P2: P2_code.c
	gcc -o P2 P2_code.c

T01 : all
	./P2 < ./P2-tests/T01/input

T02 : all
	./P2 < ./P2-tests/T02/input

T03 : all
	./P2 < ./P2-tests/T03/input

T04 : all
	./P2 < ./P2-tests/T04/input

clean :
	rm P2